/**
 * Chat-specific error codes
 */
export enum ChatErrorCode {
  UNKNOWN = 'UNKNOWN',
  NETWORK_ERROR = 'NETWORK_ERROR',
  MESSAGE_SEND_FAILED = 'MESSAGE_SEND_FAILED',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_MESSAGE = 'INVALID_MESSAGE',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  PAGINATION_FAILED = 'PAGINATION_FAILED',
}
