/**
 * Chat-specific error codes
 */
export enum ChatErrorCode {
  NETWORK_ERROR = 'NETWORK_ERROR',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  MESSAGE_SEND_FAILED = 'MESSAGE_SEND_FAILED',
  PAGINATION_FAILED = 'PAGINATION_FAILED',
}
